#!/bin/bash
cordova platform remove android \
&& cordova platform remove browser \
&& cordova plugin add cordova-plugin-device \
&& cordova plugin add cordova-plugin-networkinterface \
&& cordova plugin add cordova-plugin-file \
&& cordova platform add android@12.0.1 \
&& cordova build \
&& cordova run android
